#!/usr/bin/env python3
"""Offline clean-checkout consumer rehearsal -- catalog shape + offline audit
(SS-188 / BL-096 / TEST-018 / AC-021 / AC-030 / AC-032 / AC-034 / AC-036).

Dependency-free, no toolchain required. Two guarantees:

  shape -- `tools/catalogs/consumer_rehearsal.tsv` (regenerated by the live
      `scripts/contract_matrix`-style toolchain run `scripts/consumer_rehearsal`)
      has exactly one row per (mode, order, backend) in {workspace,
      installed} x {forward, reverse} x {c, vm} -- 8 rows -- and no row
      claims `result=fail` (a real failure must be caught live, never
      checked in, same discipline as `check_contract_matrix.py`).

  offline -- `scripts/consumer_rehearsal` never invokes a network-fetching
      command. Its only two ways of obtaining source are the dev
      checkout already on disk and `git clone --local` (which reads the
      target's `.git` directly and never touches the network). A
      network primitive appearing in the script would silently break the
      "no network access" half of TEST-018 without any other check
      noticing.

Wired into `scripts/check`.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
COLUMNS = ["mode", "order", "backend", "result", "note"]
MODES = ["workspace", "installed"]
ORDERS = ["forward", "reverse"]
BACKENDS = ["c", "vm"]
RESULTS = {"pass", "fail"}

NETWORK_RE = re.compile(
    r"\bcurl\b|\bwget\b|\bnc\s+-|\bftp://|https?://(?!github\.com/sv0-toolchain)|"
    r"git\s+(clone|fetch|pull)\s+(?!--local\b)(?!.*--local\b)"
)


def is_comment(line: str) -> bool:
    return line.lstrip().startswith("#")


def main() -> int:
    errs: list[str] = []

    p = REPO / "tools" / "catalogs" / "consumer_rehearsal.tsv"
    with p.open(encoding="utf-8") as f:
        r = csv.DictReader(f, delimiter="\t")
        header = r.fieldnames or []
        rows = list(r)
    if header != COLUMNS:
        print(f"check_consumer_rehearsal: header {header} != {COLUMNS}", file=sys.stderr)
        return 1

    seen: set[tuple[str, str, str]] = set()
    for i, row in enumerate(rows, start=2):
        key = (row["mode"], row["order"], row["backend"])
        where = f"consumer_rehearsal.tsv:{i} ({key})"
        if key in seen:
            errs.append(f"{where}: duplicate row")
        seen.add(key)
        if row["mode"] not in MODES:
            errs.append(f"{where}: mode {row['mode']!r} not in {MODES}")
        if row["order"] not in ORDERS:
            errs.append(f"{where}: order {row['order']!r} not in {ORDERS}")
        if row["backend"] not in BACKENDS:
            errs.append(f"{where}: backend {row['backend']!r} not in {BACKENDS}")
        if row["result"] not in RESULTS:
            errs.append(f"{where}: result {row['result']!r} not in {sorted(RESULTS)}")
        elif row["result"] == "fail":
            errs.append(f"{where}: a checked-in 'fail' is itself a gate error -- "
                        "run scripts/consumer_rehearsal and fix the real regression")

    want = {(m, o, b) for m in MODES for o in ORDERS for b in BACKENDS}
    for miss in sorted(want - seen):
        errs.append(f"missing rehearsal row for {miss}")
    for extra in sorted(seen - want):
        errs.append(f"unexpected rehearsal row for {extra}")

    script = (REPO / "scripts" / "consumer_rehearsal").read_text(encoding="utf-8")
    for lineno, line in enumerate(script.splitlines(), start=1):
        if is_comment(line):
            continue
        if NETWORK_RE.search(line):
            errs.append(f"scripts/consumer_rehearsal:{lineno}: possible network call "
                        f"(TEST-018 requires offline): {line.strip()!r}")
    if "git clone" not in script or "--local" not in script:
        errs.append("scripts/consumer_rehearsal: expected an offline "
                    "'git clone --local' for the installed-mode checkout")

    if errs:
        for e in errs:
            print(f"check_consumer_rehearsal: {e}", file=sys.stderr)
        print(f"check_consumer_rehearsal: {len(errs)} error(s)", file=sys.stderr)
        return 1

    print(f"check_consumer_rehearsal: OK -- {len(rows)} rows (2 modes x 2 orders x "
          "2 backends), 0 fail, no network call detected in scripts/consumer_rehearsal.")
    for row in rows:
        print(f"  {row['mode']:<10} {row['order']:<8} {row['backend']:<3} {row['result']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
