#!/usr/bin/env python3
"""Generate ``docs/compatibility.md`` from the traceability catalogs
(SPEC BL-070 / DOC-004 / AC-016).

``docs/compatibility.md`` is a **generated** artifact: it is a rebuild of
``tools/catalogs/standards.tsv`` + ``tools/catalogs/requirements.tsv`` +
``tools/catalogs/tests.tsv`` and MUST NOT be a separately drifting
hand-maintained claim (DOC-004). ``--check`` regenerates in memory and
byte-compares against the committed file (nonzero exit on drift) -- the
"generated-file digest/rebuild test". Dependency-free (stdlib only) and
needs no SPEC checkout, so ``scripts/check`` can run it unconditionally.

Usage:
    tools/compat_doc.py [--out PATH] [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOGS = REPO / "tools" / "catalogs"
OUT_DEFAULT = REPO / "docs" / "compatibility.md"

# Requirements with no executed-test row, and why that is correct. Keyed by id.
ANNOTATIONS = {
    "C23-002": "Vacuous: **0** C23 `<string.h>` functions carry the `Exact` "
               "disposition, so there is no Exact output to differential-test. "
               "This generator fails if that ever stops being true without a "
               "covering differential row.",
    "C23-019": "Deferred to **SS-154** (warnings-as-errors + ASan/UBSan + fuzz "
               "+ safe-UB audit); tracked, not yet closed.",
    "C23K-002": "`Future` release. Annex K is **Excluded** from the core claim "
                "(every `_s` symbol absent -- pinned by "
                "`test/compile_fail/c23_annex_k_absent.sv0`), so this "
                "\"if implemented\" clause is not applicable at R0.3.",
    "C23K-003": "`Future` release. Not applicable while Annex K is Excluded "
                "(see C23K-002).",
}


def read_tsv(name: str) -> tuple[list[str], list[list[str]]]:
    lines = (CATALOGS / name).read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    rows = [ln.split("\t") for ln in lines[1:] if ln.strip()]
    return header, rows


def col(header: list[str], row: list[str], key: str) -> str:
    return row[header.index(key)].strip()


def build() -> str:
    sh, srows = read_tsv("standards.tsv")
    rh, rrows = read_tsv("requirements.tsv")
    th, trows = read_tsv("tests.tsv")

    # requirement id -> sorted list of covering test ids
    covers: dict[str, list[str]] = {}
    for r in trows:
        tid = col(th, r, "id")
        for rid in (x.strip() for x in col(th, r, "requirements").split(",") if x.strip()):
            covers.setdefault(rid, []).append(tid)
    for rid in covers:
        covers[rid] = sorted(covers[rid])

    c23_fns = [r for r in srows if col(sh, r, "standard") == "C23"
               and col(sh, r, "classification") not in ("declaration",)]
    c23_decls = [r for r in srows if col(sh, r, "standard") == "C23"
                 and col(sh, r, "classification") == "declaration"]
    annexk = [r for r in srows if col(sh, r, "standard") == "C23-AnnexK"]

    exact_fns = [col(sh, r, "symbol") for r in c23_fns if col(sh, r, "disposition") == "Exact"]

    out: list[str] = []
    w = out.append

    w("# C23 `<string.h>` compatibility matrix")
    w("")
    w("<!-- GENERATED by tools/compat_doc.py from tools/catalogs/*.tsv -- do not")
    w("     hand-edit. Run `tools/compat_doc.py` to rebuild; `scripts/check`")
    w("     runs `--check` to fail on drift (SPEC DOC-004). -->")
    w("")
    w("This file is a **rebuild of catalog data**, not a separate claim. Every")
    w("row below is derived from `tools/catalogs/standards.tsv` (dispositions,")
    w("from SPEC Appendix A), `tools/catalogs/requirements.tsv` (the C23-001 ..")
    w("C23-030 / C23K rows), and `tools/catalogs/tests.tsv` (which fixtures")
    w("cover which requirement).")
    w("")

    w("## 1. Core C23 §7.26 declarations")
    w("")
    w("| declaration | classification | disposition |")
    w("|---|---|---|")
    for r in c23_decls:
        w(f"| `{col(sh, r, 'symbol')}` | {col(sh, r, 'classification')} | {col(sh, r, 'disposition')} |")
    w("")
    w("Safe-façade mapping is `docs/c23-header-surface.md` (`size_t` -> `usize`,")
    w("`NULL` -> `Option::None` / absence, `__STDC_VERSION_STRING_H__` not")
    w("provided by the safe surface).")
    w("")

    w("## 2. Core C23 §7.26 functions")
    w("")
    w(f"{len(c23_fns)} functions, each with exactly one disposition "
      "(SPEC C23-001, machine-checked by `tools/standards_matrix.py`).")
    w("")
    w("| function | category | disposition |")
    w("|---|---|---|")
    for r in sorted(c23_fns, key=lambda x: col(sh, x, "symbol")):
        w(f"| `{col(sh, r, 'symbol')}` | {col(sh, r, 'classification')} | {col(sh, r, 'disposition')} |")
    w("")
    from collections import Counter
    dc = Counter(col(sh, r, "disposition") for r in c23_fns)
    w("Disposition totals: " + ", ".join(f"**{k}** {v}" for k, v in sorted(dc.items())) + ".")
    w("")
    if exact_fns:
        w(f"`Exact` functions: {', '.join('`' + s + '`' for s in exact_fns)} "
          "-- each MUST have a differential row (C23-002).")
    else:
        w("No function carries the `Exact` disposition, so C23-002 (differential "
          "match for Exact outputs) is vacuous.")
    w("")

    w("## 3. Optional C23 Annex K profile")
    w("")
    w("Annex K is optional in C23 and **Excluded** from this library's core")
    w("claim. No safe module exports any `_s` symbol; symbol-absence is pinned")
    w("by `test/compile_fail/c23_annex_k_absent.sv0` (C23K-001).")
    w("")
    w("| symbol / type | disposition |")
    w("|---|---|")
    for r in annexk:
        w(f"| `{col(sh, r, 'symbol')}` | {col(sh, r, 'disposition')} |")
    w("")

    w("## 4. C23 requirement coverage (C23-001 .. C23-030, C23K)")
    w("")
    w("| id | release | covering evidence |")
    w("|---|---|---|")
    c23_reqs = [r for r in rrows if col(rh, r, "id").startswith("C23")]
    for r in c23_reqs:
        rid = col(rh, r, "id")
        rel = col(rh, r, "release")
        verif = col(rh, r, "verification")
        tests = covers.get(rid, [])
        if tests:
            ev = ", ".join(f"`{t}`" for t in tests)
        elif rid in ANNOTATIONS:
            ev = ANNOTATIONS[rid]
        else:
            # non-test verification method taken straight from the spec row
            ev = f"non-test: {verif.rstrip('.')}"
        w(f"| {rid} | {rel} | {ev} |")
    w("")

    w(f"{len(c23_reqs)} C23 requirement rows: every row above resolves to a "
      "covering fixture, a non-test verification method (review / inventory), "
      "an explicit vacuity note, or a tracked deferral -- none is silently "
      "unaddressed (SPEC AC-016).")
    w("")

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=OUT_DEFAULT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    text = build()

    if args.check:
        have = args.out.read_text(encoding="utf-8") if args.out.is_file() else ""
        if have != text:
            print(f"compat_doc: {args.out.name} is stale vs the catalogs "
                  f"-- run tools/compat_doc.py", file=sys.stderr)
            return 1
        print(f"compat_doc: {args.out.name} up to date")
        return 0

    args.out.write_text(text, encoding="utf-8")
    print(f"compat_doc: wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
